In [204]:
from numpy import array, sqrt
from numpy.linalg import inv, norm

In [205]:
def yakobi(x: list, x0):
    lam = x[4]
    return array([[(2 * lam + 1), 0, 2, 0, 2 * x[0] - 2 * x0[0]],
                  [0, (2 * lam + 1), 0, 0, 2 * x[1] - 2 * x0[1]],
                  [2, 0, (2 * lam + 1), 0, 2 * x[2] - 2 * x0[2]],
                  [0, 0, 0, (2 * lam + 1), 2 * x[3] - 2 * x0[3]],
                  [2 * x[0] - 2 * x0[0], 2 * x[1] - 2 * x0[1], 2 * x[2] - 2 * x0[2], 2 * x[3] - 2 * x0[3], 0]])

In [206]:
def f(x: list):
    return 1 / 2 * sum(x[i] ** 2 for i in range(0, 3 + 1)) + 2 * x[0] * x[2] + sum(x[i] for i in range(0, 3 + 1))

In [207]:
def g(x, x0, r):
    return sum((x[i] - x0[i]) ** 2 for i in range(0, 3 + 1)) - r ** 2

In [208]:
def F(x: list, x0, r):
    lam = x[4]
    return f(x) + lam * g(x, x0, r)

In [209]:
def nablaF(x, x0, r):
    lamb = x[4]
    return array([(2 * lamb + 1) * x[0] + 2 * x[2] - 2 * lamb * x0[0] + 1,
                  (2 * lamb + 1) * x[1] - 2 * lamb * x0[1] + 1,
                  (2 * lamb + 1) * x[2] + 2 * x[0] - 2 * lamb * x0[2] + 1,
                  (2 * lamb + 1) * x[3] - 2 * lamb * x0[3] + 1,
                  sum(x[i] ** 2 - 2 * x0[i] * x[i] for i in range(0, 3 + 1)) - r ** 2 + sum(x0[i] ** 2 for i in range(0, 3 + 1))])

In [210]:
def lenNablaF(x, x0, r):
    nabl = nablaF(x, x0, r)
    return norm(nabl)

In [211]:
def x_new(xk, yak, Fxk):
    return xk - inv(yak) @ Fxk

Решения

In [212]:
r_c = 5

lambda_b = 1

point_b = [0, 0, 0, 0]

eps_r = 1

eps = 0.001

for a_c in range(point_b[0] - r_c - eps_r, point_b[0] + r_c + eps_r + 1):
    for b_c in range(point_b[1] - r_c - eps_r, point_b[1] + r_c + eps_r + 1):
        for c_c in range(point_b[2] - r_c - eps_r, point_b[2] + eps_r + 1):
            for d_c in range(point_b[3] - r_c - eps_r, point_b[3] + r_c + eps_r + 1):
                point = [a_c, b_c, c_c, d_c, lambda_b]
                while lenNablaF(point, point_b, r_c) > eps:
                    yak = yakobi(point, point_b)
                    Fcur = nablaF(point, point_b, r_c)
                    point = x_new(point, yak, Fcur)
                print(point, f(point))

[-0.43763011 -3.50834433 -0.43763011 -3.50834433 -0.35748263] 4.991091409612412
[-0.43763011 -3.50834437 -0.43763011 -3.50834432 -0.35748264] 4.991091483936547
[-0.43763012 -3.50834408 -0.43763012 -3.50834489 -0.35748267] 4.991092175273195
[-0.43763052 -3.50833125 -0.43763052 -3.50838008 -0.35748398] 4.991148524911467
[-0.43763011 -3.50834445 -0.43763011 -3.50834427 -0.35748264] 4.991091534676658
[-0.43763024 -3.50835595 -0.43763024 -3.50833874 -0.35748308] 4.991106625832927
[-0.43763011 -3.5083443  -0.43763011 -3.50834436 -0.35748263] 4.9910914009723655
[-0.43763014 -3.5083426  -0.43763014 -3.50834689 -0.35748277] 4.991093498293598
[-0.4376314  -3.5083766  -0.4376314  -3.50834111 -0.35748834] 4.991165071585308
[-0.43763011 -3.5083443  -0.43763011 -3.50834435 -0.35748263] 4.991091377225754
[-0.43763011 -3.50834466 -0.43763011 -3.50834411 -0.35748264] 4.991091661094931
[-0.43763011 -3.50834459 -0.43763011 -3.50834423 -0.35748264] 4.991091793046257
[-0.43763011 -3.50834432 -0.43763011 -3

LinAlgError: Singular matrix